library(shiny)
library(shinythemes)

shinyUI(navbarPage(title = "dpcReport",
                   theme = shinytheme("cerulean"),
                   id = "navbar", windowTitle = "dpcReport", collapsible=TRUE,
                   tabPanel("Input file",
                            includeMarkdown("input_file1.md"),
                            fluidRow(
                              column(2, fileInput("input_file", 
                                                  h4("Choose dPCR data"))),
                              column(2, selectInput("input_type", label = h4("Select data format"), 
                                                    choices = list("Raw data (adpcr)" = "raw_adpcr", 
                                                                   "Raw data (ddpcr)" = "raw_ddpcr",
                                                                   "QX100" = "QX100",
                                                                   "BioMark (Detailed Table Results)" = "BioMark_det",
                                                                   "BioMark (Summary Table Results)" = "BioMark_sum"))),
                              column(3, htmlOutput("input_information"))
                            ),
                            includeMarkdown("input_file2.md"),
                            fluidRow(
                              column(3, h4("Experiment name"), htmlOutput("exp_choice")),
                              column(3, h4("Technical repeat ID"), htmlOutput("rep_choice"))
                            )
                   ),
                   navbarMenu("Data summary",
                              tabPanel("Summary table", 
                                       dataTableOutput("summary_input"),
                                       includeMarkdown("./data_summary/data_summary_table1.md")),
                              #summary boxplot and stripchart
                              tabPanel("Summary charts", 
                                       includeMarkdown("./summary_plots/data_summary_scatterchart1.md"),
                                       selectInput("CI_method", label = h4("Select method for CI calculation:"), 
                                                   choices = list("Dube" = "dube", "Bhat" = "bhat")),
                                       plotOutput("summary_plot", 
                                                  dblclick = dblclickOpts(id = "summary_plot_dbl")),
                                       br(),
                                       htmlOutput("summary_plot_dbl"),
                                       includeMarkdown("./summary_plots/data_summary_scatterchart2.md"),
                                       htmlOutput("summary_exprep_plot_ui"),
                                       htmlOutput("summary_exprep_plot_dbl"))),
                   #test counts
                   tabPanel("Comparison of runs", 
                            includeMarkdown("./test_counts/test_counts1.md"),
                            dataTableOutput("test_counts_res"),
                            includeMarkdown("./test_counts/test_counts2.md"),
                            dataTableOutput("test_counts_groups"),
                            htmlOutput("test_counts_plot_ui"),
                            htmlOutput("test_count_dbl"),
                            includeMarkdown("./test_counts/test_counts3.md")),
                   navbarMenu("Advanced analysis",
                              tabPanel(title = "Array spatial analysis", 
                                       htmlOutput("plot_panel_tab")),
                              tabPanel(title = "Probability distribution", 
                                       includeMarkdown("./prob_distr/prob_distr1.md"),
                                       htmlOutput("run_choice"),
                                       includeMarkdown("./prob_distr/prob_distr2.md"),
                                       dataTableOutput("moments_table"),
                                       includeMarkdown("./prob_distr/prob_distr3.md"),
                                       fluidRow(
                                         column(3, selectInput("density_plot_avg", label = h4("Select parameter:"), 
                                                               choices = c("k" = FALSE, "lambda" = TRUE))),
                                         
                                         column(3, selectInput("density_plot_methods", h4("Choose method of calculating CI:"), 
                                                               choices  = list("Exact" = "exact", 
                                                                               "Agresti-Coull" = "agresti-coull", 
                                                                               "Asymptotic" = "asymptotic", 
                                                                               "Wilson" = "wilson", 
                                                                               "Proportion test" = "prop.test", 
                                                                               "Bayesian inference"  = "bayes", 
                                                                               "Logit parameterization" = "logit", 
                                                                               "cloglog parameterization" = "cloglog", 
                                                                               "probit parameterization" = "probit"), 
                                                               "wilson")),
                                         column(3, numericInput("density_plot_cil", h4("Confidence intervals level:"), 
                                                                0.95, min = 0, max = 1,
                                                                step = 0.01)),
                                         column(3, selectInput("density_plot_bars", label = h4("Plot bars:"), 
                                                               choices = c("yes" = TRUE, "no" = FALSE)))
                                       ),
                                       plotOutput("density_plot"),
                                       includeMarkdown("./prob_distr/prob_distr4.md")
                              )
                   ),
                   tabPanel("Download report",
                            includeMarkdown("download_report1.md"),
                            checkboxInput("data_summary_table_rep", "Data summary table", 
                                          value = TRUE),
                            checkboxInput("data_summary_scatter_rep", "Data summary scatter charts", 
                                          value = TRUE),
                            checkboxInput("data_summary_test_counts", "Compare runs", 
                                          value = TRUE),
                            checkboxInput("plot_panel", "Visualise and analyze individually each array", 
                                          value = FALSE),
                            checkboxInput("poisson_distr", "Visualise and analyze probability distribution of each run", 
                                          value = FALSE),
                            checkboxInput("R_code", "R code used in the report generation", 
                                          value = TRUE),
                            downloadButton("report_download_button", 
                                           "Download report")),
                   tabPanel("About", 
                            includeMarkdown("about.md")),
                   tabPanel("Quit", actionButton("quit_button", "Press buttton if you want to quit dpcReport"))
))
